In [3]:
import numpy as np
import matplotlib.pyplot as plt 
from scipy.spatial.distance import cdist
np.random.seed(2)

In [4]:
means = [[2,2], [4,2]]
cov = [[.3,.2],[.2,.3]]
N=10
X0 = np.random.multivariate_normal(means[0], cov, N).T
X1 = np.random.multivariate_normal(means[1], cov, N).T

X = np.concatenate((X0, X1), axis=1)
y = np.concatenate((np.ones((1, N)), -1*np.ones((1,N))), axis=1)

X = np.concatenate((np.ones((1, 2*N)), X), axis=0)

In [5]:
X

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [2.22096057, 2.70132234, 3.08493823, 2.02701417, 2.73223639,
        1.21171968, 2.22920603, 1.8637762 , 1.74682699, 2.37191737,
        4.47403369, 4.09281249, 4.22222334, 4.58438569, 4.74493118,
        3.6355797 , 5.19217738, 3.51075436, 3.93784332, 3.8787214 ],
       [2.19579728, 3.43487375, 2.70849736, 1.47010441, 2.32571583,
        2.23682627, 1.72925457, 1.59716548, 2.27230351, 2.37595358,
        2.4040742 , 1.65061706, 2.11659863, 2.05326933, 2.67628604,
        2.63347726, 3.2425902 , 2.11880111, 1.56029947, 2.12126884]])

In [6]:
X0

array([[2.22096057, 2.70132234, 3.08493823, 2.02701417, 2.73223639,
        1.21171968, 2.22920603, 1.8637762 , 1.74682699, 2.37191737],
       [2.19579728, 3.43487375, 2.70849736, 1.47010441, 2.32571583,
        2.23682627, 1.72925457, 1.59716548, 2.27230351, 2.37595358]])

In [7]:
y

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1.]])

In [8]:
def h(w, x):
    return np.sign(np.dot(w.T, x))

In [9]:
def has_converged(X, y, w):
    return np.array_equal(h(w, X), y)

In [10]:
def perceptron(X, y, w_init):
    w = [w_init]
    N = X.shape[1]
    d = X.shape[0]
    mis_points = []
    while True:
        mix_id = np.random.permutation(N)
        for i in range(N):
            xi = X[:, mix_id[i]].reshape(d,1)
            yi = y[0, mix_id[i]]
            if h(w[-1], xi)[0] != yi:
                mis_points.append(mix_id[i])
                w_new = w[-1] + yi*xi
                w.append(w_new)
        if has_converged(X, y, w[-1]):
            break
    return (w, mis_points)

In [13]:
d = X.shape[0]
w_init = np.random.randn(d,1)
(w, m) = perceptron(X, y, w_init)

In [14]:
w_init

array([[-0.3135082 ],
       [ 0.77101174],
       [-1.86809065]])